config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about"=>"homes#about"
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only:[:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
        member do
          get :followings ,:followers
        end
  end

  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @bookshow = Book.find(params[:book_id])
    @favorite = current_user.favorites.new(book_id: @bookshow.id)
    @favorite.save
  end

  def destroy
    @bookshow = Book.find(params[:book_id])
    @favorite = current_user.favorites.find_by(book_id: @bookshow.id)
    @favorite.destroy
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>

  <%= link_to book_favorites_path(book.id),method: :delete, remote: true do %>
    <p class="text-danger">♥<%= book.favorites.count %></p>
  <% end %>

<% else %>

  <%= link_to book_favorites_path(book.id),method: :post, remote: true do %>
    <p class="text-primary">♥<%= book.favorites.count %></p>
  <% end %>

<% end %>

app/views/favorites/create.js.erb
$(".favorite_btn").html("<%= j(render "favorites/favorite", book: @bookshow) %>");
$('#favorite_btns<%= @bookshow.id %>').html("<%= j(render "favorites/favorite", book: @bookshow) %>");

app/views/favorites/destroy.js.erb
$(".favorite_btn").html("<%= j(render "favorites/favorite", book: @bookshow) %>");
$('#favorite_btns<%= @bookshow.id %>').html("<%= j(render "favorites/favorite", book: @bookshow) %>");