config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about"=>"homes#about"
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only:[:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
        member do
          get :followings ,:followers
        end
  end

  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment ,presence:true

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @bookshow =Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comments_params)
    @comment.book_id = @bookshow.id
    @comment.save
  end

  def destroy
    @bookshow =Book.find(params[:book_id])
    @comment = current_user.book_comments.find_by(book_id: @bookshow.id)
    @comment.destroy
  end

  private

  def book_comments_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment.html.erb
  <table>
    <tbody>

        <% bookshow.book_comments.each do |book_comment| %>
          <tr>
          <td>
          <%= image_tag book_comment.user.get_profile_image, size: '50x50' %><br>
          <%= link_to book_comment.user.name,user_path(book_comment.user) %>
          </td>
          <td>
          <%= book_comment.comment %>
          </td>
          <td>
          <%= link_to book_book_comment_path(book_comment.book,book_comment), method: :delete, remote: true do %>
            <btn class ="btn btn-sm btn-danger">"Destroy"</btn>
          <% end %>
          </td>

          </tr>
        <% end %>

    </tbody>
  </table>

app/views/book_comments/create.js.erb
$("textarea").val("");

$('#comments-all<%= @bookshow.id %>').html("<%= j(render "book_comments/comment", bookshow: @bookshow, book_comment: @book_comment) %>");

$(".comment-count").html("コメント数：<%= @bookshow.book_comments.count %>");

app/views/book_comments/destroy.js.erb
$('#comments-all<%= @bookshow.id %>').html("<%= j(render "book_comments/comment", bookshow: @bookshow, book_comment: @book_comment) %>");

$(".comment-count").html("コメント数：<%= @bookshow.book_comments.count %>");