config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "homes#top"
  get "home/about"=>"homes#about"
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  
  devise_for :users

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only:[:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
      resource :relationships, only: [:create, :destroy]
        member do
          get :followings ,:followers
        end
  end

  get "search" => "searches#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  has_many :sns_credential, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  has_many :follower, class_name: "Relationship",foreign_key: "follower_id",dependent: :destroy
  has_many :followings,through: :follower, source: :followed

  has_many :followed, class_name: "Relationship" ,foreign_key: "followed_id",dependent: :destroy
  has_many :followers,through: :followed, source: :follower

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length:{maximum: 50 }

  # 検索窓
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def self.guest
    find_or_create_by!(name: "guestuser",email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  # フォローしたときの処理
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  # フォローを外すときの処理
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  # フォローしているか判定
  def followings?(user)
    followings.include?(user)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @followings = @user.followings
    @followers = @user.followers

  end

  def index
    @users = User.all
    @book = Book.new
    @followings = current_user.followings
    @followers = current_user.followers
    @user = current_user
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  # フォロー一覧
  def followings
    @user = User.find(params[:id])
    @users = @user.followings
  end

  # フォロワー一覧
  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user),notice: "ゲストユーザーはプロフィール編集画面へ遷移できません。"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<div class="container">
  <table class='table'>
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% users.each do |user| %>
        <tr>
          <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
          <td><%= user.name %></td>
          <td>フォロー数：<%= user.followings.count %></td>
          <td>フォロワー数:<%= user.followers.count %></td>
          <td>
             <% if user != current_user %>
              <% if current_user.followings?(user) %>
                <%= link_to "フォロー外す",user_relationships_path(user.id), method: :delete %>
              <% else %>
                <%= link_to "フォローする",user_relationships_path(user.id), method: :post %>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to 'Show', user %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="pagetop">
  <div class="row d-flex flex-column">
    <div class="col text-center"><i class="h4 fas fa-sort-up mb-0"></i></div>
    <div class="col">Top</div>
  </div>
</div>

<script>
  const pagetop_btn = document.querySelector(".pagetop");
  pagetop_btn.addEventListener("click",scroll_top);
  function scroll_top(){
    window.scroll({top:0, behavior:"smooth"});
  }
</script>

app/views/users/_info.html.erb
<div class="container">

  <table class='table'>
    <tr><%= image_tag user.get_profile_image, size: '100x100' %></tr>
    <tr>
  	  <th>name</th>
  	  <th><%= user.name %></th>
    </tr>
    <tr>
  	  <th>introduction</th>
  	  <th><%= user.introduction %></th>
    </tr>
    <tr>
      <td>follows</td>
      <td><%= link_to user.followings.count,followings_user_path(user.id) %></td>
    </tr>
    <tr>
      <td>followers</td>
      <td><%= link_to user.followers.count,followers_user_path(user.id) %></td>
    </tr>
  </table>
  <% if (user == current_user) && (user.name != "guestuser") %>
    <div class='row'>
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    </div>
  <% elsif user != current_user %>
      <% if current_user.followings?(user) %>
        <%= link_to "フォロー外す",user_relationships_path(user.id), class: "btn btn-info", method: :delete %>
      <% else %>
        <%= link_to "フォローする",user_relationships_path(user.id), class: "btn btn-success", method: :post %>
      <% end %>
  
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class='container px-5 px-sm-0'>
<h2>Follower Users</h2>
<% if @users.exists? %>

<table class='table'>
  <thead>
  <th>
    <td>
      image
    </td>
    <td>
      neme
    </td>
    <td></td>
    <td></td>
  </th>
  </thead>
 <tbody>
   <% @users.each do |user| %>
  <tr>
    <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
    <td><%= user.name %></td>
    <td>フォロー数：<%= user.followings.count %></td>
    <td>フォロワー数:<%= user.followers.count %></td>
    <td><%= link_to 'Show', user_path(user.id) %></td>
  </tr>
  <% end %>
  </tbody>
</table>

<% else %>
  <p>ユーザーはいません</p>
<% end %>
</div>

app/views/users/followings.html.erb
<div class='container px-5 px-sm-0'>
<h2>Follow Users</h2>
<% if @users.exists? %>

<table class='table'>
  <thead>
  <th>
    <td>
      image
    </td>
    <td>
      neme
    </td>
    <td></td>
    <td></td>
  </th>
  </thead>
 <tbody>
   <% @users.each do |user| %>
  <tr>
    <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
    <td><%= user.name %></td>
    <td>フォロー数：<%= user.followings.count %></td>
    <td>フォロワー数:<%= user.followers.count %></td>
    <td><%= link_to 'Show', user_path(user.id) %></td>
  </tr>
  <% end %>
  </tbody>
</table>

<% else %>
  <p>ユーザーはいません</p>
<% end %>
</div>

app/views/users/index.html.erb
<div class= "container px-5">
  <div class="row">
    <div class="col-md-3">
    <h2>User info</h2>
    <%= render 'info', user: @user ,followers: @followers, followings: @followings %>

    <h2 class="mt-3">New book</h2>
    <%= render 'books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <%= render 'index',users: @users, followers: @followers, followings: @followings %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user , followers: @followers, followings: @followings %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>